version: "3.9"

services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  gateway:
    build: ./gateway
    ports:
      - 8082:8082
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - DEBUG=true
    depends_on:
      - discovery

  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    ports:
      - 8081:8081
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
      - DEBUG=true
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    depends_on:
      - discovery

  parties:
    build:
      context: .
      dockerfile: Dockerfile-parties
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
      - DEBUG=true
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    depends_on:
      - discovery