# Utilisez une image Java officielle en tant que base
FROM eclipse-temurin:17-jdk

# Définir le répertoire de travail
WORKDIR /app

COPY ./modeleGestionUtilisateurs/ /app/modeleGestionUtilisateurs/
COPY ./joueur/ /app/joueur/

WORKDIR /app/modeleGestionUtilisateurs/

RUN /app/joueur/mvnw clean install

WORKDIR /app/joueur/

# Exécutez Maven pour construire l'application
RUN ./mvnw clean package -DskipTests=true

# Définir le point d'entrée de l'application
CMD java -jar target/joueur-0.0.1-SNAPSHOT.jar