# Utilisez une image Java officielle en tant que base
FROM eclipse-temurin:17-jdk

# Définir le répertoire de travail
WORKDIR /app

COPY ./modeleGestionParties/ /app/modeleGestionParties/
COPY ./parties/ /app/parties/

WORKDIR /app/modeleGestionParties/

RUN /app/parties/mvnw clean install

WORKDIR /app/parties/

# Exécutez Maven pour construire l'application
RUN ./mvnw clean package -DskipTests=true

# Définir le point d'entrée de l'application
CMD java -jar target/parties-0.0.1-SNAPSHOT.jar