GET http://localhost:8080/parties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiQm9iIiwiZXhwIjoxNzA1NjU2NDQ5LCJpYXQiOjE3MDU2NTI4NDksInNjb3BlIjoiIn0.RD6xeMDK0kfwZOEM6J2cxoMbKLywo2DOw1iVnwmMJHrW2UZQW6ozYt6mYzge2Z6AOal2pUUP3rlasrQ0GPsOPHl6GG2QF7eUaLTSucklBBgRzHZhHgU3qJlySPX9rHZWPahBrW0-zuiz0a8_gjf5k_F2ESGEjpKtwo24NRJM6gF4emskpM7wBX95-yQWvyeM8NnSmD0eoTEfOIYQ6IkP_BrKwwS2PvwDLUWZPIgybalEpxAD3dPxleg3j9wUPryNbU9i35kbskjFs4GciVbi_gCKb3sAEioqQC50MqQcKop51n55Tru6VWg5-XmBP0591UAs9obrDSc2DhECJRL_GQ

###

GET http://localhost:8080/joueurs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiQm9iIiwiZXhwIjoxNzA1NjU2NDQ5LCJpYXQiOjE3MDU2NTI4NDksInNjb3BlIjoiIn0.RD6xeMDK0kfwZOEM6J2cxoMbKLywo2DOw1iVnwmMJHrW2UZQW6ozYt6mYzge2Z6AOal2pUUP3rlasrQ0GPsOPHl6GG2QF7eUaLTSucklBBgRzHZhHgU3qJlySPX9rHZWPahBrW0-zuiz0a8_gjf5k_F2ESGEjpKtwo24NRJM6gF4emskpM7wBX95-yQWvyeM8NnSmD0eoTEfOIYQ6IkP_BrKwwS2PvwDLUWZPIgybalEpxAD3dPxleg3j9wUPryNbU9i35kbskjFs4GciVbi_gCKb3sAEioqQC50MqQcKop51n55Tru6VWg5-XmBP0591UAs9obrDSc2DhECJRL_GQ

###

DELETE http://localhost:8080/joueurs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiQm9iIiwiZXhwIjoxNzA1NjU2NDQ5LCJpYXQiOjE3MDU2NTI4NDksInNjb3BlIjoiIn0.RD6xeMDK0kfwZOEM6J2cxoMbKLywo2DOw1iVnwmMJHrW2UZQW6ozYt6mYzge2Z6AOal2pUUP3rlasrQ0GPsOPHl6GG2QF7eUaLTSucklBBgRzHZhHgU3qJlySPX9rHZWPahBrW0-zuiz0a8_gjf5k_F2ESGEjpKtwo24NRJM6gF4emskpM7wBX95-yQWvyeM8NnSmD0eoTEfOIYQ6IkP_BrKwwS2PvwDLUWZPIgybalEpxAD3dPxleg3j9wUPryNbU9i35kbskjFs4GciVbi_gCKb3sAEioqQC50MqQcKop51n55Tru6VWg5-XmBP0591UAs9obrDSc2DhECJRL_GQ

###

POST http://localhost:8080/parties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiQm9iIiwiZXhwIjoxNzA1NjU2NDQ5LCJpYXQiOjE3MDU2NTI4NDksInNjb3BlIjoiIn0.RD6xeMDK0kfwZOEM6J2cxoMbKLywo2DOw1iVnwmMJHrW2UZQW6ozYt6mYzge2Z6AOal2pUUP3rlasrQ0GPsOPHl6GG2QF7eUaLTSucklBBgRzHZhHgU3qJlySPX9rHZWPahBrW0-zuiz0a8_gjf5k_F2ESGEjpKtwo24NRJM6gF4emskpM7wBX95-yQWvyeM8NnSmD0eoTEfOIYQ6IkP_BrKwwS2PvwDLUWZPIgybalEpxAD3dPxleg3j9wUPryNbU9i35kbskjFs4GciVbi_gCKb3sAEioqQC50MqQcKop51n55Tru6VWg5-XmBP0591UAs9obrDSc2DhECJRL_GQ

{
  "choix": "1"
}

###

GET http://localhost:8080/statistiques
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiQm9iIiwiZXhwIjoxNzA1NjU2NDQ5LCJpYXQiOjE3MDU2NTI4NDksInNjb3BlIjoiIn0.RD6xeMDK0kfwZOEM6J2cxoMbKLywo2DOw1iVnwmMJHrW2UZQW6ozYt6mYzge2Z6AOal2pUUP3rlasrQ0GPsOPHl6GG2QF7eUaLTSucklBBgRzHZhHgU3qJlySPX9rHZWPahBrW0-zuiz0a8_gjf5k_F2ESGEjpKtwo24NRJM6gF4emskpM7wBX95-yQWvyeM8NnSmD0eoTEfOIYQ6IkP_BrKwwS2PvwDLUWZPIgybalEpxAD3dPxleg3j9wUPryNbU9i35kbskjFs4GciVbi_gCKb3sAEioqQC50MqQcKop51n55Tru6VWg5-XmBP0591UAs9obrDSc2DhECJRL_GQ